### ISSUE TITLE
The game is laggy on the latest update from unleashed (0.60)

### ISSUE THREAD

**Issue by thiago-s-medeiros** [teeebor/flipper_solitaire#6]
Hey @teeebor, hello again!

I'm seeing some lag on the game after this new update (maybe in the update that brought the store to the flipper app), kind of running smoothly for 5s and then I need to wait a long time to move the selector again, and then, it repeats this behavior...

This could be my flipper or is this happening with you too?

**Comment by teeebor** [comment]
Hi!
Did you get it from the store? Because I did not made it compatible with it yet. Also, no, the game shouldn't slow down after any time and the navigation should be instant, there is no long running or parallel logic present in the current release. I don't have unleashed installed, but haven't noticed anything similar on ofw, I can play for hours there.

Maybe you could try to change the log level on your flipper? Anything below info level will slow down the device.

**Comment by acme4j** [comment]
I confirm, I have the same problem. I also disabled the logs at all. It didn't help.
Flipper freezes Every ~5 seconds of running Solitaire.

Firmware version: unlshd-062e [20-08-2023].

**Comment by teeebor** [comment]
Have to look into it, it seems wierd to me since I haven't touched the game in a long time. It may have some problem with something in unleashed

**Comment by teeebor** [comment]
@acme4j , @thiago-s-medeiros  can you please try the [1.1.3](https://github.com/teeebor/flipper_solitaire/releases/tag/1.1.3) release?

**Comment by acme4j** [comment]
Just tested. Works perfect!

Thank you for quick response.

**Comment by thiago-s-medeiros** [comment]
Feels like 120hz right now, hahaha, thank you!!
